import { expect, test, type Page } from '@playwright/test'

const map = (page: Page) => page.getByRole('img', { name:'Mapa político interativo de Varedor' })
const panel = (page: Page) => page.getByRole('complementary', { name:'Painel contextual' })
const province = (page: Page, id: string) => page.locator(`path[data-province="${id}"]`)

async function foundHouse(page: Page, name = 'Ravencor') {
  await page.goto('/', { waitUntil:'domcontentloaded' })
  await page.getByRole('button', { name:'Nova Campanha' }).click()
  await page.getByLabel('Nome da casa').fill(name)
  await page.getByRole('button', { name:'Continuar ›' }).click()
  await page.getByRole('button', { name:'Continuar ›' }).click()
  await page.getByRole('button', { name:'Fundar Minha Casa' }).click()
  await expect(map(page)).toBeVisible()
}
async function waitFor(page: Page, text: RegExp) {
  await page.getByTitle('Muito rápido').click()
  await expect(page.getByRole('button', { name:text }).first()).toBeVisible({ timeout:40_000 })
}

test('cria uma casa personalizada em três etapas com brasão ao vivo', async ({ page }) => {
  await page.goto('/', { waitUntil:'domcontentloaded' })
  await page.getByRole('button', { name:'Nova Campanha' }).click()
  const input = page.getByLabel('Nome da casa')
  await input.fill('Hadrin')
  await expect(page.getByText('Esta casa já existe em Varedor.')).toBeVisible()
  await expect(page.getByRole('button', { name:'Continuar ›' })).toBeDisabled()
  await input.fill('Santiago')
  await expect(page.getByText('Prévia: Casa Santiago')).toBeVisible()
  await page.getByRole('button', { name:'Continuar ›' }).click()
  await page.getByRole('button', { name:'Coroa' }).click()
  await page.getByRole('button', { name:'Partido' }).click()
  await page.getByRole('button', { name:'Principal: Azul real' }).click()
  await page.getByRole('button', { name:'Secundária: Azul real' }).click()
  await expect(page.getByText('As cores principal e secundária precisam ser diferentes.')).toBeVisible()
  await page.getByRole('button', { name:'Secundária: Ouro' }).click()
  await expect(page.getByRole('img', { name:'Brasão da Casa Santiago' })).toBeVisible()
  await expect(page.getByText('Partido · Coroa')).toBeVisible()
  await page.getByRole('button', { name:'Continuar ›' }).click()
  for (const text of ['Velária', 'Três Pontes', 'Pontevela', 'Castelo da Ponte Alta', '700', '1.240']) await expect(page.getByText(text, { exact:true }).first()).toBeVisible()
  await page.getByRole('button', { name:'Fundar Minha Casa' }).click()
  await expect(page.getByRole('button', { name:'Abrir menu' })).toContainText('Casa Santiago')
  await expect(page.getByRole('navigation', { name:'Modos de jogo' }).getByRole('button')).toHaveText(['Descobrir', 'Influenciar', 'Conquistar'])
})

test('mostra províncias, fronteiras e névoa, com zoom contínuo e arraste', async ({ page }) => {
  await page.setViewportSize({ width:1440, height:860 })
  await foundHouse(page)
  expect(await page.locator('path[data-province]').count()).toBe(252)
  expect(await page.locator('path[data-knowledge="0"]').count()).toBeGreaterThan(230)
  await expect(page.locator('[data-player-seat]')).toHaveCount(1)
  expect(await page.locator('[data-layer="realm-borders"] > g').count()).toBe(7)
  expect(await page.locator('[data-layer="fief-borders"] > g').count()).toBe(42)
  expect(await page.locator('[data-explorable]').count()).toBeGreaterThan(3)
  await expect(page.locator('[data-province-label]')).toHaveText(['Pontevela'])
  // Every settlement type has an icon.
  await page.getByRole('button', { name:'Aproximar' }).click()
  await page.getByRole('button', { name:'Aproximar' }).click()
  const icons = await page.locator('[data-map-building] use').evaluateAll(nodes => nodes.map(node => node.getAttribute('href')))
  expect(icons.length).toBe(4)
  for (const href of icons) expect(await page.locator(`symbol${href}`).count()).toBe(1)
  await expect(page.locator('text[data-province-label]')).toHaveCount(1)
  // Wheel zoom and drag move only the camera.
  const scale = Number(await map(page).getAttribute('data-scale'))
  await page.mouse.move(500, 450); await page.mouse.wheel(0, 600)
  await expect.poll(async () => Number(await map(page).getAttribute('data-scale'))).toBeLessThan(scale)
  const layer = map(page).locator(':scope > g').first()
  const before = await layer.getAttribute('transform')
  await page.mouse.move(500, 450); await page.mouse.down(); await page.mouse.move(580, 480, { steps:8 }); await page.mouse.up()
  await expect(layer).not.toHaveAttribute('transform', before!)
  await expect(panel(page).getByRole('heading', { name:'Fronteiras de Varedor' })).toBeVisible()
  // The calendar advancing never resets the camera.
  const moved = await layer.getAttribute('transform')
  await page.getByTitle('Muito rápido').click(); await page.waitForTimeout(700); await page.getByTitle('Pausar').click()
  await expect(layer).toHaveAttribute('transform', moved!)
})

test('ciclo completo do MVP persiste após salvar e carregar', async ({ page }) => {
  test.setTimeout(180_000)
  await page.setViewportSize({ width:1440, height:860 })
  await foundHouse(page, 'Draven')
  // Invest in the province economy.
  await page.getByRole('button', { name:'Influenciar' }).click()
  await panel(page).locator('[data-investment="market"]').getByRole('button', { name:/Investir/ }).click()
  await expect(panel(page).getByText(/Em obras · 25 dias restantes/)).toBeVisible()
  await expect(page.locator('[data-resource="gold"] strong')).toHaveText('480')
  // Send an expedition to a sighted frontier.
  await page.getByRole('button', { name:'Descobrir' }).click()
  const target = (await page.locator('[data-explorable]').first().getAttribute('data-explorable'))!
  await province(page, target).dispatchEvent('click')
  await expect(panel(page).getByRole('heading', { name:'Terras avistadas' })).toBeVisible()
  await panel(page).getByRole('button', { name:/Enviar expedição/ }).click()
  await expect(page.locator(`[data-expedition-marker="${target}"]`)).toBeVisible()
  await waitFor(page, /Expedição concluída/)
  await expect(page.locator(`path[data-province="${target}"]`)).toHaveAttribute('data-knowledge', '2')
  await province(page, target).dispatchEvent('click')
  await expect(panel(page).getByText('Relatório da expedição')).toBeVisible()
  // Diplomacy: send an emissary and meet the ruler.
  await panel(page).getByRole('button', { name:/Enviar emissário/ }).click()
  await waitFor(page, /Primeiro contato/)
  await province(page, target).dispatchEvent('click')
  await expect(panel(page).getByText('Por que esta relação?')).toBeVisible()
  await panel(page).getByRole('button', { name:/Enviar presente/ }).click()
  await panel(page).getByRole('button', { name:/Conversar com/ }).click()
  await panel(page).getByRole('button', { name:'Cumprimentar' }).click()
  await expect(panel(page).locator('[aria-live="polite"]')).toContainText('Amizade')
  await expect(panel(page).getByRole('button', { name:/Cumprimentar/ })).toBeDisabled()
  // Espionage: hire and send an agent.
  await panel(page).getByRole('button', { name:'‹ Voltar' }).click()
  await panel(page).getByRole('button', { name:/^‹/ }).first().click()
  await panel(page).getByRole('tab', { name:'Espiões' }).click()
  await panel(page).locator('[data-agent="agent-0"]').getByRole('button', { name:/Contratar/ }).click()
  await province(page, target).dispatchEvent('click')
  await panel(page).getByRole('button', { name:/Enviar Nara/ }).click()
  await waitFor(page, /Relatório —/)
  await province(page, target).dispatchEvent('click')
  await expect(panel(page).locator(`[data-report="${target}"]`).first()).toContainText('Fonte: Nara')
  // Save, start over, load: everything is back.
  const day = await page.locator('header').getByTitle(/Dia/).innerText()
  await page.getByRole('button', { name:'Abrir menu' }).click()
  await page.getByRole('button', { name:'Salvar', exact:true }).click()
  await page.getByRole('button', { name:'Salvar campanha' }).click()
  await expect(page.getByText(/Campanha salva/)).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name:'Carregar campanha' }).click()
  await page.getByRole('button', { name:/^Campanha da Casa Draven/ }).click()
  await expect(page.getByRole('button', { name:'Abrir menu' })).toContainText('Casa Draven')
  await expect(page.locator('header').getByTitle(/Dia/)).toHaveText(day)
  await expect(page.locator(`path[data-province="${target}"]`)).toHaveAttribute('data-knowledge', /[23]/)
  await page.getByRole('button', { name:'Influenciar' }).click()
  await panel(page).getByRole('tab', { name:'Espiões' }).click()
  await expect(panel(page).getByText('Fonte: Nara', { exact:false }).first()).toBeVisible()
  await panel(page).getByRole('tab', { name:'Relações' }).click()
  await expect(panel(page).getByText(/Neutra|Amigável|Desconfiada|Hostil/).first()).toBeVisible()
})

test('a audiência do castelo e os dados de Pontevela continuam disponíveis', async ({ page }) => {
  await page.setViewportSize({ width:1440, height:860 })
  await foundHouse(page)
  await page.locator('[data-player-seat]').waitFor()
  await province(page, 'province-019').dispatchEvent('click')
  await expect(panel(page).getByRole('heading', { name:'Pontevela' })).toBeVisible()
  await panel(page).getByRole('button', { name:/Castelo da Ponte Alta/ }).click()
  await expect(panel(page).getByText('Guarnição').locator('..')).toContainText('75')
  await page.getByRole('button', { name:'Influenciar' }).click()
  await panel(page).getByRole('button', { name:/Visitar o Castelo da Ponte Alta/ }).click()
  await expect(page.getByRole('heading', { name:'Castelo da Ponte Alta' })).toBeVisible()
  const art = page.getByRole('img', { name:/Intendente no salão de Pontevela/ })
  await expect(art).toBeVisible()
  expect(await art.evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  await page.getByRole('button', { name:/Distribuir mantimentos/ }).click()
  const scene = page.getByRole('heading', { name:'Castelo da Ponte Alta' }).locator('..')
  await expect(scene.getByText('82%', { exact:true })).toBeVisible()
  await expect(page.getByText(/Casa Ravencor distribuiu cento e vinte sacas/).first()).toBeVisible()
  await page.getByRole('button', { name:'Voltar ao mapa' }).click()
  await expect(page.locator('[data-resource="food"] strong')).toHaveText('1.120')
})

test('o modo Conquistar mostra forças reais e não oferece ações militares', async ({ page }) => {
  await foundHouse(page)
  await page.getByRole('button', { name:'Conquistar' }).click()
  await expect(panel(page).getByText('Em desenvolvimento')).toBeVisible()
  await expect(panel(page).getByText('325', { exact:true })).toBeVisible()
  // Only the panel's collapse control: no military orders are offered.
  await expect(panel(page).getByRole('button')).toHaveCount(1)
  await expect(page.locator('[data-garrison="province-019"]')).toBeVisible()
})

test('celular na horizontal: mapa em tela cheia, painel compacto e toque', async ({ browser }) => {
  const context = await browser.newContext({ viewport:{ width:844, height:390 }, hasTouch:true, isMobile:true })
  const page = await context.newPage()
  await foundHouse(page, 'Serraval')
  const box = (await map(page).boundingBox())!
  expect(box.width).toBe(844); expect(box.height).toBe(390)
  expect(await page.evaluate(() => document.body.scrollWidth)).toBe(844)
  await expect(panel(page)).toHaveCount(0)
  await expect(page.getByRole('button', { name:/Expedições 0\/2/ })).toBeVisible()
  const target = (await page.locator('[data-explorable]').first().getAttribute('data-explorable'))!
  await province(page, target).dispatchEvent('click')
  await expect(panel(page)).toBeVisible()
  const panelBox = (await panel(page).boundingBox())!
  expect(panelBox.width).toBeLessThan(844 / 2)
  await panel(page).getByRole('button', { name:'Recolher painel' }).click()
  await expect(panel(page)).toHaveCount(0)
  for (const label of ['Descobrir', 'Influenciar', 'Conquistar']) await expect(page.getByRole('button', { name:label })).toBeInViewport()
  await context.close()
})

test('a arte do atlas carrega e os barcos navegam respeitando movimento reduzido', async ({ page }) => {
  await page.setViewportSize({ width:1600, height:900 })
  await foundHouse(page)
  expect(await page.evaluate(async () => { const image = new Image(); image.src = '/assets/varedor-map-atlas.png'; await image.decode(); return image.naturalWidth })).toBeGreaterThan(1000)
  await expect(page.locator('use[href="#art-tree"],use[href="#art-pine"],use[href="#art-mountain"]')).toHaveCount(0)
  const ship = page.locator('[data-ship]').first()
  const position = () => ship.evaluate(el => { const m = (el as SVGGraphicsElement).getCTM()!; return { x:m.e, y:m.f } })
  const start = await position()
  await expect.poll(async () => { const next = await position(); return Math.hypot(next.x - start.x, next.y - start.y) }, { timeout:6000 }).toBeGreaterThan(2)
  await page.emulateMedia({ reducedMotion:'reduce' })
  await expect(page.locator('[data-sailing]')).toHaveAttribute('data-sailing', 'paused')
  const paused = await position()
  await page.waitForTimeout(300)
  expect(await position()).toEqual(paused)
})
