import { expect, test } from '@playwright/test'

test('abre apenas o mapa e permite entrar no território pelo clique', async ({ page }) => {
  test.setTimeout(60_000)
  await page.goto('/', { waitUntil:'domcontentloaded' })
  await expect(page.getByRole('img', { name:'Mapa político interativo de Varedor' })).toBeVisible()
  await expect(page.getByRole('complementary')).toHaveCount(0)
  await page.locator('path[data-territory="realm-1"]').first().click()
  await expect(page.getByRole('complementary', { name:'Detalhes do território' }).getByRole('heading', { name:'Velária' })).toBeVisible()
  await page.getByRole('button', { name:/Três Pontes/ }).click()
  await expect(page.getByRole('complementary').getByRole('heading', { name:'Três Pontes' })).toBeVisible()
  await page.getByRole('button', { name:/Pontevela/ }).click()
  await expect(page.getByRole('complementary').getByRole('heading', { name:'Pontevela' })).toBeVisible()
  await page.getByRole('complementary', { name:'Detalhes do território' }).getByRole('button', { name:/Castelo da Ponte Alta/ }).click()
  await expect(page.getByText('Guarnição')).toBeVisible()
  await expect(page.getByText('75', { exact:true })).toBeVisible()
  await page.getByRole('button', { name:/Entrar em Pontevela/ }).click()
  await expect(page.getByRole('heading', { name:'Castelo da Ponte Alta' })).toBeVisible()
  const audienceArt=page.getByRole('img', { name:/Intendente no salão de Pontevela/ })
  await expect(audienceArt).toBeVisible()
  expect(await audienceArt.evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0)
  await expect(page.getByText('Crônica local')).toBeVisible()
  await page.getByRole('button', { name:/Distribuir mantimentos/ }).click()
  await expect(page.getByText('82%', { exact:true })).toBeVisible()
  await expect(page.getByText(/distribuiu cento e vinte sacas/).first()).toBeVisible()
  await page.getByRole('button', { name:'Voltar ao mapa' }).click()
  await page.getByRole('button', { name:'Fechar detalhes' }).click()
  await expect(page.getByRole('complementary')).toHaveCount(0)
})

test('o menu oculto controla o calendário e os salvamentos', async ({ page }) => {
  test.setTimeout(90_000)
  await page.goto('/', { waitUntil:'domcontentloaded' })
  await page.getByRole('button', { name:'Abrir menu' }).click()
  const date=page.getByText(/Dia \d+ · 128 AP/)
  await expect(date).toContainText('Dia 1 · 128 AP')
  await page.getByTitle('Muito rápido').click()
  await expect(date).not.toContainText('Dia 1 · 128 AP')
  await page.getByTitle('Pausar').click()
  const savedDate=await date.innerText()
  await page.getByRole('button', { name:'Salvar', exact:true }).click()
  await page.getByRole('button', { name:'Salvar campanha' }).click()
  await expect(page.getByText(/Campanha salva/)).toBeVisible()
  await page.getByRole('button', { name:'Abrir menu' }).click()
  await page.getByRole('button', { name:'Nova campanha' }).click()
  await page.getByRole('button', { name:'Iniciar como Casa Serraval' }).click()
  await page.getByRole('button', { name:'Abrir menu' }).click()
  await expect(date).toContainText('Dia 1 · 128 AP')
  await page.getByRole('button', { name:'Carregar' }).click()
  await page.getByRole('button', { name:/^Campanha de Serraval/ }).click()
  await page.getByRole('button', { name:'Abrir menu' }).click()
  await expect(date).toHaveText(savedDate)
})

test('no celular o mapa continua sendo a primeira tela', async ({ page }) => {
  await page.setViewportSize({width:390,height:844})
  await page.goto('/', { waitUntil:'domcontentloaded' })
  const map=page.getByRole('img', { name:'Mapa político interativo de Varedor' })
  await expect(map).toBeVisible()
  expect((await map.boundingBox())!.height).toBeGreaterThan(800)
  await expect(page.getByRole('complementary')).toHaveCount(0)
  expect(await page.locator('body').evaluate(body => body.scrollWidth)).toBe(390)
})

test('arrastar o mapa move a câmera sem abrir território', async ({ page }) => {
  await page.goto('/', { waitUntil:'domcontentloaded' })
  const map=page.getByRole('img', { name:'Mapa político interativo de Varedor' })
  const terrain=map.locator(':scope > g').first()
  const before=await terrain.getAttribute('transform')
  await page.mouse.move(800,450)
  await page.mouse.down()
  await page.mouse.move(875,475,{steps:8})
  await page.mouse.up()
  await expect(terrain).not.toHaveAttribute('transform',before!)
  await expect(page.getByRole('complementary')).toHaveCount(0)
})

test('a arte carrega, capitais ficam livres dos rótulos e barcos navegam', async ({page})=>{
  await page.setViewportSize({width:1600,height:900})
  await page.goto('/',{waitUntil:'networkidle'})
  expect(await page.evaluate(async()=>{const image=new Image();image.src='/assets/varedor-map-atlas.png';await image.decode();return image.naturalWidth})).toBeGreaterThan(1000)
  await expect(page.locator('use[href="#art-tree"],use[href="#art-pine"],use[href="#art-mountain"]')).toHaveCount(0)
  const collisions=await page.evaluate(()=>{
    const buildings=[...document.querySelectorAll('[data-map-building]')]
    const labels=[...document.querySelectorAll('[data-map-label]')]
    return buildings.flatMap(building=>{
      const sprite=building.querySelector('use')!,matrix=sprite.getScreenCTM()!
      const topLeft=new DOMPoint(sprite.x.baseVal.value,sprite.y.baseVal.value).matrixTransform(matrix)
      const bottomRight=new DOMPoint(sprite.x.baseVal.value+sprite.width.baseVal.value,sprite.y.baseVal.value+sprite.height.baseVal.value).matrixTransform(matrix)
      const caption=building.querySelector('text')?.getBoundingClientRect()
      const a={left:Math.min(topLeft.x,caption?.left??Infinity),right:Math.max(bottomRight.x,caption?.right??-Infinity),top:topLeft.y,bottom:Math.max(bottomRight.y,caption?.bottom??-Infinity)}
      return labels.filter(label=>{const b=label.getBoundingClientRect();return a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top}).map(label=>[building.getAttribute('data-map-building'),label.getAttribute('data-map-label')])
    })
  })
  expect(collisions).toEqual([])
  const ship=page.locator('[data-ship]').first()
  const position=()=>ship.evaluate(el=>{const m=(el as SVGGraphicsElement).getCTM()!;return {x:m.e,y:m.f}})
  const start=await position()
  await expect.poll(async()=>{const next=await position();return Math.hypot(next.x-start.x,next.y-start.y)},{timeout:6000}).toBeGreaterThan(2)
  await page.emulateMedia({reducedMotion:'reduce'})
  await expect(page.locator('[data-sailing]')).toHaveAttribute('data-sailing','paused')
  const paused=await position()
  await page.waitForTimeout(300)
  expect(await position()).toEqual(paused)
})
