import type { GameState,Id } from './types'
import type { DialogueTopic } from './mvpTypes'
import {BALANCE} from './balance'
import {editGame,requireRule,nextId,clamp,playerHouse} from './stateUtils'
import {canConverse,characterName} from './characters'
import {reveal,sightNeighbors} from './knowledge'
import {notify} from './notifications'
export const TOPICS:Record<DialogueTopic,string>={greet:'Cumprimentar',house:'Perguntar sobre sua casa',region:'Perguntar sobre a região',politics:'Conversar sobre política',compliment:'Elogiar',favor:'Solicitar um favor simples'}
export function dialogueWait(g:GameState,id:Id,topic:DialogueTopic){const last=g.campaign.conversations.filter(c=>c.characterId===id&&c.topic===topic).at(-1);return last?Math.max(0,last.day+(topic==='favor'?BALANCE.dialogue.favorCooldown:BALANCE.dialogue.cooldown)-g.day):0}
export function converse(game:GameState,id:Id,topic:DialogueTopic){const original=game.campaign.characters.find(c=>c.id===id);requireRule(original&&canConverse(game,original),'Estabeleça contato antes de conversar com este personagem.');requireRule(TOPICS[topic],'Conversa inválida.');requireRule(dialogueWait(game,id,topic)===0,'Aguarde antes de repetir este assunto.');const g=editGame(game),c=g.campaign.characters.find(c=>c.id===id)!,p=g.world.provinces.find(p=>p.id===c.provinceId)!,h=g.world.houses.find(h=>h.id===c.houseId)!;const contact=g.campaign.contacts.find(d=>d.houseId===c.houseId);const cold=c.traits.includes('desconfiado')||(contact?.relation??0)<0;const ambition=c.traits.includes('ambicioso');const prefix=cold?'Sejamos prudentes. ':ambition?'Há muito a alcançar. ':'É bom receber sua palavra. ';const memory=c.memory.at(-1);let response='',consequence='';
 switch(topic){case 'greet':response=memory?`Lembro-me: ${memory.text} Podemos continuar nossa conversa.`:`Sou ${characterName(g,c)}, ${c.role.toLowerCase()}. ${cold?'A confiança se conquista.':'Sua visita é bem-vinda.'}`;c.relationship.friendship=clamp(c.relationship.friendship+(cold?1:3));consequence=`Amizade +${cold?1:3}.`;break;
 case 'house':response=`${h.name} tem sede em ${g.world.provinces.find(p=>p.id===h.seatProvinceId)!.name}. “${h.motto}” ${h.memory[0]??''}`;reveal(g,h.seatProvinceId,'explorada','Conversa com a casa');sightNeighbors(g,h.seatProvinceId);c.relationship.trust=clamp(c.relationship.trust+2);consequence='Sede identificada; confiança +2.';break;
 case 'region':response=`${p.name} é uma região de ${p.terrain}. ${g.world.settlements.filter(s=>s.provinceId===p.id).slice(0,2).map(s=>s.name).join(' e ')} sustentam a vida local. ${g.world.roads.some(r=>r.includes(p.id))?'Estradas ligam nossas terras aos vizinhos.':'O acesso exige cuidado.'}`;reveal(g,p.id,'investigada',`Conversa com ${c.name}`);sightNeighbors(g,p.id);consequence='Conhecimento regional atualizado e fronteiras avistadas.';break;
 case 'politics':response=`Nosso juramento é à ${g.world.houses.find(h=>h.id===p.liegeHouseId)!.name}. ${ambition?'Desejo ampliar nossa influência.':cold?'Não confio em promessas apressadas.':'A estabilidade favorece nossa gente.'} ${contact?`Entre nossas casas, a relação está em ${contact.relation}.`:''}`;c.relationship.respect=clamp(c.relationship.respect+2);playerHouse(g).influence+=1;consequence='Respeito +2; influência +1.';break;
 case 'compliment':response=cold?'Bela retórica. Prefiro julgar seus atos.':ambition?'Seu reconhecimento chegará longe.':'Recebo suas palavras com gratidão.';c.relationship.friendship=clamp(c.relationship.friendship+(cold?1:5));c.relationship.trust=clamp(c.relationship.trust+(cold?0:2));consequence=`Amizade +${cold?1:5}${cold?'':'; confiança +2'}.`;break;
 case 'favor':{const yes=c.relationship.trust+c.relationship.friendship+(contact?.relation??10)>=25;response=yes?'Falarei a seu favor no conselho. Honre essa confiança.':'Ainda não nos conhecemos o suficiente para isso.';if(yes){playerHouse(g).influence+=5;c.relationship.respect=clamp(c.relationship.respect+2)}else c.relationship.trust=clamp(c.relationship.trust-1);consequence=yes?'Favor aceito: influência +5; respeito +2.':'Pedido recusado: confiança −1.';break}}
 if(contact&&contact.audienceUntil>=g.day){c.relationship.respect=clamp(c.relationship.respect+1);consequence+=' Audiência formal: respeito +1.'}
 const memoryText=`${TOPICS[topic]}: ${consequence}`;c.memory.push({day:g.day,text:memoryText});c.memory=c.memory.slice(-30);g.campaign.conversations.push({id:nextId(g,'conversation'),characterId:id,day:g.day,topic,response:prefix+response,consequence});notify(g,`Conversa com ${c.name}`,consequence,p.id);return g
}
