import type { GameState,Id } from './types'
import {BALANCE} from './balance'
import {editGame,spend,nextId,requireRule,clamp,playerHouse} from './stateUtils'
import {knowledge,knownRoute,reveal} from './knowledge'
import {initialRelation,disposition} from './relationships'
import {notify} from './notifications'
export function diplomacyQuote(g:GameState,id:Id){return BALANCE.diplomacy.days+Math.max(0,knownRoute(g,id).length-2)*2}
export function sendEmissary(game:GameState,id:Id){const p=game.world.provinces.find(p=>p.id===id);requireRule(p&&knowledge(game,id)>=2&&knownRoute(game,id).length,'Descubra uma rota terrestre até essa província.');requireRule(p.governingHouseId!==game.playerHouseId,'Esta é sua própria casa.');requireRule(!game.campaign.contacts.some(c=>c.houseId===p.governingHouseId),'Contato já iniciado.');const g=editGame(game);spend(g,BALANCE.diplomacy.gold);const context=initialRelation(g,p.governingHouseId,id);g.campaign.contacts.push({houseId:p.governingHouseId,provinceId:id,establishedDay:null,...context,lastGiftDay:null,audienceUntil:-1,trade:false});g.campaign.diplomacy.push({id:nextId(g,'diplomacy'),kind:'emissary',houseId:p.governingHouseId,provinceId:id,startDay:g.day,endDay:g.day+diplomacyQuote(g,id),completed:false});notify(g,'Emissário a caminho',`A comitiva segue para ${p.name}.`,id);return g}
export function diplomaticAction(game:GameState,houseId:Id,action:'gift'|'rapprochement'|'audience'|'trade'){
 const contact=game.campaign.contacts.find(c=>c.houseId===houseId);requireRule(contact&&contact.establishedDay!==null,'Primeiro estabeleça contato por emissário.');const g=editGame(game),c=g.campaign.contacts.find(c=>c.houseId===houseId)!,h=g.world.houses.find(h=>h.id===houseId)!;
 if(action==='gift'){requireRule(c.lastGiftDay===null||g.day-c.lastGiftDay>=BALANCE.diplomacy.giftCooldown,'Espere 30 dias entre presentes.');spend(g,BALANCE.diplomacy.giftGold);h.gold+=BALANCE.diplomacy.giftGold;c.lastGiftDay=g.day;c.relation=clamp(c.relation+10);g.campaign.influence[houseId]=clamp((g.campaign.influence[houseId]??0)+BALANCE.influence.gift.gain,0,100);const ruler=g.campaign.characters.find(ch=>ch.id===`ruler-${houseId}`)!;ruler.memory.push({day:g.day,text:`Recebeu um presente de ${playerHouse(g).name}.`});ruler.relationship.trust=clamp(ruler.relationship.trust+3);notify(g,'Presente recebido',`${h.name} agradeceu o presente. Relação +10.`,c.provinceId)}
 else if(action==='trade'){requireRule(!c.trade&&c.relation>=0&&knownRoute(g,c.provinceId).length>0,'O comércio exige relação não hostil e uma rota terrestre descoberta.');c.trade=true;notify(g,'Acordo comercial',`${h.name}: +${BALANCE.diplomacy.tradeIncome} ouro por mês enquanto a relação permanecer não hostil e a rota válida.`,c.provinceId)}
 else {requireRule(!g.campaign.diplomacy.some(d=>d.houseId===houseId&&d.kind===action&&!d.completed),'Uma solicitação desse tipo já está em andamento.');requireRule(action!=='audience'||c.audienceUntil<g.day,'A audiência já está disponível.');requireRule(!g.campaign.diplomacy.some(d=>d.houseId===houseId&&d.kind===action&&g.day-d.startDay<30),'Espere 30 dias entre solicitações.');g.campaign.diplomacy.push({id:nextId(g,'diplomacy'),kind:action,houseId,provinceId:c.provinceId,startDay:g.day,endDay:g.day+(action==='rapprochement'?BALANCE.diplomacy.rapprochementDays:BALANCE.diplomacy.audienceDays),completed:false});notify(g,'Pedido diplomático enviado',action==='audience'?'A corte avaliará seu pedido de audiência.':'A comitiva apresenta interesses em comum.',c.provinceId)}return g
}
export function processDiplomacy(g:GameState){for(const d of g.campaign.diplomacy)if(!d.completed&&d.endDay<=g.day){d.completed=true;const c=g.campaign.contacts.find(c=>c.houseId===d.houseId)!,h=g.world.houses.find(h=>h.id===d.houseId)!;if(d.kind==='emissary'){c.establishedDay=g.day;reveal(g,d.provinceId,'investigada','Contato diplomático');notify(g,'Primeiro contato',`${h.name}: recepção ${disposition(c.relation).toLowerCase()} (${c.relation}). ${c.reasons.join('; ')}.`,d.provinceId,true)}else if(d.kind==='rapprochement'){const gain=c.relation<-25?2:8;c.relation=clamp(c.relation+gain);notify(g,'Aproximação concluída',`${h.name}: relação +${gain}. ${c.relation<0?'A cautela persiste.':'Há interesses em comum.'}`,d.provinceId)}else {const accepted=c.relation>=-15;if(accepted)c.audienceUntil=g.day+BALANCE.diplomacy.audienceWindow;const char=g.campaign.characters.find(ch=>ch.id===`ruler-${d.houseId}`)!;char.memory.push({day:g.day,text:accepted?'Concedeu uma audiência.':'Recusou um pedido de audiência.'});notify(g,accepted?'Audiência concedida':'Audiência recusada',accepted?'Durante 30 dias, conversas nesta corte concedem respeito adicional.':'A relação deve melhorar antes de uma audiência formal.',d.provinceId,true)}}}
