import type { GameState,Id } from './types'
import {BALANCE} from './balance'
import {hash} from './random'
import {editGame,requireRule,spend,nextId,clamp} from './stateUtils'
import {knowledge,knownRoute,reveal} from './knowledge'
import {notify} from './notifications'
export function hireSpy(game:GameState,id:Id){const agent=game.campaign.agents.find(a=>a.id===id);requireRule(agent&&!agent.hired,'Agente indisponível.');requireRule(game.campaign.agents.filter(a=>a.hired).length<BALANCE.spy.max,'Limite de três agentes.');const g=editGame(game);spend(g,BALANCE.spy.gold);g.campaign.agents.find(a=>a.id===id)!.hired=true;notify(g,'Agente contratado',`${g.campaign.characters.find(c=>c.id===agent.characterId)!.name} recebe 6 ouro/mês.`);return g}
export function spyQuote(g:GameState,id:Id){const route=knownRoute(g,id);return {route,days:BALANCE.spy.days+Math.max(0,route.length-2),gold:BALANCE.spy.missionGold}}
export function sendSpy(game:GameState,agentId:Id,provinceId:Id){const a=game.campaign.agents.find(a=>a.id===agentId),quote=spyQuote(game,provinceId);requireRule(a?.hired,'Contrate este agente primeiro.');requireRule(knowledge(game,provinceId)>=2&&quote.route.length,'É necessária uma província conhecida com rota terrestre.');requireRule(!game.campaign.spyMissions.some(m=>m.agentId===agentId&&!m.completed),'Este agente já está em missão.');const g=editGame(game);spend(g,quote.gold);g.campaign.spyMissions.push({id:nextId(g,'spy-mission'),agentId,provinceId,startDay:g.day,endDay:g.day+quote.days,completed:false,route:quote.route});notify(g,'Investigação iniciada',`O agente deverá retornar em ${quote.days} dias.`,provinceId);return g}
export function processEspionage(g:GameState){for(const m of g.campaign.spyMissions)if(!m.completed&&m.endDay<=g.day){m.completed=true;const a=g.campaign.agents.find(a=>a.id===m.agentId)!,c=g.campaign.characters.find(c=>c.id===a.characterId)!,p=g.world.provinces.find(p=>p.id===m.provinceId)!,h=g.world.houses.find(h=>h.id===p.governingHouseId)!;const defender=g.campaign.characters.find(c=>c.id===`ruler-${h.id}`)!;const roll=hash(`${g.world.seed}:${m.id}:${m.startDay}:${p.id}`)%100;const score=roll+c.intrigue*.55+a.loyalty*.15-defender.intrigue*.2-p.loyalty*.1;m.outcome=score>=82?'sucesso':score>=57?'parcial':score>=35?'nada':'identificado';const full=m.outcome==='sucesso',partial=m.outcome==='parcial';const treasury=full?Math.round(h.gold/50)*50:undefined,garrison=full||partial?Math.round(g.world.settlements.filter(s=>s.provinceId===p.id).reduce((n,s)=>n+s.garrison,0)/25)*25:undefined;const relations=g.campaign.contacts.find(d=>d.houseId===h.id);const text=full?`Tesouro estimado: ${treasury} ouro. Guarnição aproximada: ${garrison}. Lealdade observada: ${p.loyalty}. Juramento à ${g.world.houses.find(h=>h.id===p.liegeHouseId)!.name}.${p.loyalty<60?' A população parece insatisfeita, e há rumores de que o senhor local perde apoio.':p.loyalty>80?' O povo parece fiel ao senhor local.':''}${relations?` A corte comenta nossa relação (${relations.relation}).`:''}`:partial?`As observações indicam cerca de ${garrison} soldados na guarnição. Os livros do tesouro não puderam ser consultados.`:m.outcome==='nada'?'O agente não obteve informações verificáveis.':'O agente foi identificado e precisou abandonar a investigação. Relação com a casa local −15; lealdade do agente −5.';if(full)reveal(g,p.id,'investigada',`Agente ${c.name}`);if(m.outcome==='identificado'){a.loyalty=clamp(a.loyalty-5,0,100);const contact=g.campaign.contacts.find(d=>d.houseId===h.id);if(contact)contact.relation=clamp(contact.relation-15);h.memory.push(`Identificou um agente a serviço da ${g.world.houses.find(x=>x.id===g.playerHouseId)!.name}.`);c.memory.push({day:g.day,text:`Foi identificado em ${p.name}.`})}
 g.campaign.reports.push({id:nextId(g,'intelligence'),provinceId:p.id,day:g.day,source:c.name,confidence:full?'alta':partial?'média':'baixa',expiresDay:g.day+BALANCE.spy.reportValidity,outcome:m.outcome,text,treasury,garrison,loyalty:full?p.loyalty:undefined,rumor:full&&p.loyalty<60?'Descontentamento popular (rumor)':undefined});notify(g,`Relatório — ${p.name}`,text,p.id,true)}}
