import type { Point } from './types'
export interface RealmTemplate { name: string; house: string; capital: string; color: string; accent: string; culture: string; specialty: string; symbol: string; motto: string; anchor: Point; fiefs: [string, string][] }
export const REALMS: RealmTemplate[] = [
  { name:'Velária', house:'Trevis', capital:'Alvenor', color:'#e4b743', accent:'#ffe69a', culture:'Nobreza tradicional e obrigações feudais', specialty:'Agricultura e grandes mercados', symbol:'♜', motto:'A terra recorda', anchor:[370,235], fiefs:[['Lumeira','Dastel'],['Campos de Viora','Neravel'],['Três Pontes','Hadrin'],['Lago do Sino','Elvaren'],['Vale Cevado','Mercol'],['Colinas de Bronze','Traviel']] },
  { name:'Namaris', house:'Velmare', capital:'Sarvona', color:'#2a90ad', accent:'#9be9ea', culture:'Aristocracia mercantil e cidades portuárias', specialty:'Comércio marítimo e construção naval', symbol:'≋', motto:'A maré nos conduz', anchor:[200,385], fiefs:[['Arquipélago de Sal','Mardel'],['Coroa das Marés','Nofel'],['Falésias Azuis','Dael'],['Portos Brancos','Selmar'],['Cabo dos Sinos','Lorena'],['Ilhas Baixas','Kelto']] },
  { name:'Cársida', house:'Aurden', capital:'Karvoss', color:'#8363a5', accent:'#e0c0f0', culture:'Fortalezas, artífices e tradição militar', specialty:'Mineração e metalurgia', symbol:'⚒', motto:'A pedra resiste', anchor:[837,176], fiefs:[['Altas Forjas','Brenvek'],['Pedra Fria','Malgren'],['Passo do Ferro','Karden'],['Vale dos Martelos','Odrik'],['Cristas Altas','Felvar'],['Minas Velhas','Drenor']] },
  { name:'Orvêndia', house:'Halven', capital:'Verdoss', color:'#56a15a', accent:'#bdec9f', culture:'Comunidades antigas e lealdades familiares', specialty:'Madeira, caça e rios florestais', symbol:'♣', motto:'As raízes permanecem', anchor:[873,352], fiefs:[['Mata dos Ecos','Selver'],['Bosque de Arna','Deln'],['Rio dos Cedros','Verdan'],['Fronteira Verde','Talsen'],['Vale Nebuloso','Renfal'],['Colinas do Musgo','Ormen']] },
  { name:'Surnath', house:'Azeren', capital:'Damar', color:'#d9754b', accent:'#ffc28b', culture:'Cavaleiros e famílias rurais móveis', specialty:'Cavalos, pastagens e rotas terrestres', symbol:'✣', motto:'O horizonte é nosso', anchor:[870,537], fiefs:[['Planícies de Damar','Ravel'],['Campos do Vento','Serkan'],['Passagem Seca','Belcor'],['Colinas de Areia','Amrien'],['Vales de Cobre','Sorven'],['Prado Longo','Tarev']] },
  { name:'Dunária', house:'Brevane', capital:'Venrath', color:'#327dc2', accent:'#a7d8ff', culture:'Alianças familiares e controle de pontes', specialty:'Várzeas e transporte fluvial', symbol:'⚜', motto:'Por rios e juramentos', anchor:[360,508], fiefs:[['Baixo Delta','Nelvar'],['Ponte dos Reis','Borrel'],['Charcos de Venn','Ervoss'],['Campos Alagados','Malten'],['Rios Gêmeos','Derna'],['Barrancas Altas','Corvel']] },
  { name:'Tirâmia', house:'Essaren', capital:'Soltir', color:'#c98736', accent:'#ffe096', culture:'Diplomacia pragmática e pactos comerciais', specialty:'Caravanas e artesanato', symbol:'✦', motto:'Toda rota tem seu preço', anchor:[597,179], fiefs:[['Passos de Soltir','Morven'],['Desfiladeiro Claro','Talrik'],['Mesa Vermelha','Bralen'],['Rota dos Sinos','Eldran'],['Pedra do Sol','Arvel'],['Vale das Caravanas','Lendor']] }
]
export const FIRST_NAMES = ['Alden','Berian','Cedran','Darian','Edrin','Falor','Gavren','Halen','Irian','Jorvan','Kaelen','Lorian','Merian','Nerian','Orven','Parel','Raviel','Saren','Tavian','Valen','Weren','Ysaren']
export const PLACE_PREFIX = ['Alto','Baixo','Vale','Campo','Monte','Rio']
export const PLACE_ROOT = ['Alvar','Bruma','Cedro','Douro','Estel','Ferna','Gran','Herval','Ivora','Juncal','Lumar','Marn','Nobre','Olar','Pedra','Queral','Rossal','Sino','Torre','Ulvra','Vento','Zelar','Candeia','Freixo','Avelar','Olmedo','Castanho','Névoa','Cervo','Prata','Loureiro','Rochedo','Fontes','Salgueiro','Âmbar','Falcão','Carvalho','Estrela','Pinheiro','Corvo','Oliveira','Aurora','Limoeiro','Safira']
