import { createRoot } from 'react-dom/client'
import App from './ui/App'
import '@fontsource/cinzel/latin-500.css'
import '@fontsource/cinzel/latin-600.css'
import '@fontsource/inter/latin-400.css'
import '@fontsource/inter/latin-500.css'
import '@fontsource/inter/latin-600.css'
import '@fontsource/inter/latin-700.css'
import './ui/global.css'
createRoot(document.getElementById('root')!).render(<App />)
